ARG BASE_IMAGE_TAG

FROM docker.io/haveagitgat/tdarr_acc:base_${BASE_IMAGE_TAG}

ARG VERSION
ARG MODULE
ARG DATE
ARG USE_PROD_PACKAGES=false

ENV WEB_UI_PORT="8265" SERVER_PORT="8266" NODE_PORT="8267" PUID="1000" PGID="1000" UMASK="002" TZ="Etc/UTC" HOME="/home/Tdarr"


ENV MODULE_LINK=""
ENV NODE_LINK=""
ENV BASE_LINK=""
ENV inContainer="true"

COPY docker/root/ /
RUN chmod +x /etc/services.d/tdarr_server/run && \
    chmod +x /etc/services.d/tdarr_node/run && \
    chmod +x /etc/services.d/update_monitor/run && \
    chmod +x /etc/cont-init.d/01-setup-perms && \
    chmod +x /etc/cont-init.d/02-hw-transcoding && \
    chmod +x /etc/cont-init.d/03-setup-ffmpeg

RUN apt-get update && apt-get install -y psmisc

# handle tdarr binaries
RUN echo $MODULE && echo $VERSION && echo $DATE && echo $USE_PROD_PACKAGES && \
    if [ "$MODULE" = "Tdarr_Node" ]; then \
        echo removing /tdarr_server && \
        rm -rdf /etc/services.d/tdarr_server ; \
    fi && \

    # Set BASE_LINK based on USE_PROD_PACKAGES
    if [ "$USE_PROD_PACKAGES" = "true" ]; then \
        BASE_LINK="https://storage.tdarr.io/versions/$VERSION" && \
        FILE_SUFFIX="" ; \
    else \
        BASE_LINK="https://storage.tdarr.io/dev/versions/$VERSION" && \
        FILE_SUFFIX="_${DATE}" ; \
    fi && \

    if uname -m | grep -q x86; then \
        MODULE_LINK="${BASE_LINK}/linux_x64/${MODULE}${FILE_SUFFIX}.zip" && \
        NODE_LINK="${BASE_LINK}/linux_x64/Tdarr_Node${FILE_SUFFIX}.zip" ; \
    fi && \
    if uname -m | grep -q aarch64; then \
        MODULE_LINK="${BASE_LINK}/linux_arm64/${MODULE}${FILE_SUFFIX}.zip" && \
        NODE_LINK="${BASE_LINK}/linux_arm64/Tdarr_Node${FILE_SUFFIX}.zip" ; \
    fi && \
    if uname -m | grep -q armv7l; then \
        MODULE_LINK="${BASE_LINK}/linux_arm/${MODULE}${FILE_SUFFIX}.zip" && \
        NODE_LINK="${BASE_LINK}/linux_arm/Tdarr_Node${FILE_SUFFIX}.zip" ; \
    fi && \

    echo MODULE_LINK=$MODULE_LINK && \
    echo NODE_Link=$NODE_LINK && \
    curl --connect-timeout 120 --retry 5 -o /tmp/${MODULE}.zip -L \
    "$MODULE_LINK"  && \
    unzip -q /tmp/${MODULE}.zip -d /app/${MODULE} -x *.exe && \
    # Node
    if [ "$MODULE" = "Tdarr_Server" ]; then \
        curl --connect-timeout 120 --retry 5 -o /tmp/Tdarr_Node.zip -L \
        "$NODE_LINK" && \
        unzip -q /tmp/Tdarr_Node.zip -d /app/Tdarr_Node -x *.exe ; \
    fi && \
    rm -rdf /tmp/${MODULE}.zip && \
    rm -rdf /tmp/Tdarr_Node.zip && \
    # setup permissions 
    chmod -R 755 /app && \
    groupmod -o -g ${PGID} abc && \
    usermod -o -u ${PUID} abc && \
    chown -R abc:abc /app && \
    cp -r /app /app_test && \
    # test
    runTests=true runDockerTests=true BUILD_DATE=$DATE node /app_test/$MODULE/srcug/main.js && \
    if [ "$MODULE" = "Tdarr_Server" ]; then \
           runTests=true runDockerTests=true BUILD_DATE=$DATE node /app_test/Tdarr_Node/srcug/main.js ; \
    fi && \
    rm -rdf /app_test

EXPOSE ${NODE_PORT}
EXPOSE ${WEB_UI_PORT}
EXPOSE ${SERVER_PORT}
ENTRYPOINT ["/init"]