#!/usr/bin/with-contenv bash

# Get ffmpeg version 
installedVersion=$(ffmpeg -version 2>&1 | head -n 1 | cut -d ' ' -f 3)

echo "Installed FFmpeg version is: $installedVersion"
echo "ffmpegVersion to use is $ffmpegVersion"

if [ "$ffmpegVersion" = "5" ]; then
    echo "Using FFmpeg 5"
   
    if  uname -m | grep -q x86 && [[ "$installedVersion" != "5.1.4-Jellyfin" ]]; then
        echo "Installing ffmpeg5"
        apt remove -y jellyfin-ffmpeg6 
        apt remove -y jellyfin-ffmpeg7
        rm /usr/local/bin/ffmpeg 
        rm /usr/local/bin/tdarr-ffmpeg 

        apt install -y wget 
        ffmpegversion=5.1.4-3
        wget https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v$ffmpegversion/jellyfin-ffmpeg5_$ffmpegversion-jammy_amd64.deb
        apt install -y \
        ./jellyfin-ffmpeg5_$ffmpegversion-jammy_amd64.deb
        rm -rf ./jellyfin-ffmpeg5_$ffmpegversion-jammy_amd64.deb
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg 
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/tdarr-ffmpeg
        echo Finished
    fi
elif [ "$ffmpegVersion" = "6" ]; then
    echo "Using FFmpeg 6"
    
    if  uname -m | grep -q x86  && [[ "$installedVersion" != "6.0.1-Jellyfin" ]]; then \
        echo "Installing ffmpeg6"
        apt remove -y jellyfin-ffmpeg5 
        apt remove -y jellyfin-ffmpeg7
        rm /usr/local/bin/ffmpeg 
        rm /usr/local/bin/tdarr-ffmpeg 

        apt install -y wget
        # ffmpegversion=$(curl --silent https://api.github.com/repos/jellyfin/jellyfin-ffmpeg/releases/latest | grep -oP '"tag_name":\s*"v\K[^"]+' | sort -h | tail -n1)
        ffmpegversion=6.0.1-7
        wget https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v$ffmpegversion/jellyfin-ffmpeg6_$ffmpegversion-jammy_amd64.deb
        apt install -y \
        ./jellyfin-ffmpeg6_$ffmpegversion-jammy_amd64.deb
        rm -rf ./jellyfin-ffmpeg6_$ffmpegversion-jammy_amd64.deb
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg 
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/tdarr-ffmpeg
        echo Finished
    fi
else
    echo "Using FFmpeg 7"
    
    if  uname -m | grep -q x86  && [[ "$installedVersion" != "7.0.2-Jellyfin" ]]; then \
        echo "Installing ffmpeg7"
        apt remove -y jellyfin-ffmpeg5 
        apt remove -y jellyfin-ffmpeg6
        rm /usr/local/bin/ffmpeg 
        rm /usr/local/bin/tdarr-ffmpeg 

        apt install -y wget
        # ffmpegversion=$(curl --silent https://api.github.com/repos/jellyfin/jellyfin-ffmpeg/releases/latest | grep -oP '"tag_name":\s*"v\K[^"]+' | sort -h | tail -n1)
        ffmpegversion=7.0.2-9
        wget https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v$ffmpegversion/jellyfin-ffmpeg7_$ffmpegversion-jammy_amd64.deb
        apt install -y \
        ./jellyfin-ffmpeg7_$ffmpegversion-jammy_amd64.deb
        rm -rf ./jellyfin-ffmpeg7_$ffmpegversion-jammy_amd64.deb
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg 
        ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/tdarr-ffmpeg
        echo Finished
    fi
fi