#!/usr/bin/with-contenv bash

ARCHITECTURE=$(uname -m)
MAX_OLD_SPACE=""

if [ "$ARCHITECTURE" != "armv7l" ]; then
    MAX_OLD_SPACE="--max-old-space-size=16384"
fi

if [ -d "/etc/services.d/tdarr_server" ] && [ "$internalNode" = true ]; then \
    echo "Starting Tdarr_Node"
    exec s6-setuidgid abc node $MAX_OLD_SPACE /app/Tdarr_Node/srcug/main.js
fi

if [ ! -d "/etc/services.d/tdarr_server" ]; then \
    echo "Starting Tdarr_Node"
    exec s6-setuidgid abc node $MAX_OLD_SPACE /app/Tdarr_Node/srcug/main.js
fi
