# Shared Makefile variables

USERNAME=haveagitgat
REPO=_acc
TAG=dev

# use invalid docker tag char * so fail if not set.
DATE=***

REGISTRY=docker.io
BASE_TAG=${REGISTRY}/${USERNAME}/tdarr_acc:base
SERVER_TAG=${REGISTRY}/${USERNAME}/tdarr_acc:${TAG}
NODE_TAG=${REGISTRY}/${USERNAME}/tdarr_node_acc:${TAG}
