# Shared Makefile variables

USERNAME=haveagitgat
TAG=dev

# use invalid docker tag char * so fail if not set.
DATE=***

FIXED_BASE_TAG=2.50.02_2025_10_24T22_50_46z

REGISTRY=docker.io
BASE_TAG=${REGISTRY}/${USERNAME}/tdarr_acc:base
SERVER_TAG=${REGISTRY}/${USERNAME}/tdarr_acc:${TAG}
NODE_TAG=${REGISTRY}/${USERNAME}/tdarr_node_acc:${TAG}
