name: Publish Docker

on:
  [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: [ '1.8.1']

    steps:
    - uses: actions/checkout@2
  
    - name: Setup Meteor
      uses: meteorengineer/setup-meteor@v1.0.1
      with:
        meteor-release: ${{ matrix.meteor }}

    - name: Build meteor bundle
      run: |
        meteor npm install
        meteor build --directory Tdarr-Bundle  
       
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env:
        CI: true
      with:
        name: xchanclasox/tdarr_aio_test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ubuntu
        buildargs: CI
        tags: "latest"
