name: Publish Docker

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: [ '1.8.1']

    steps:
    - uses: actions/checkout@master
  
    - name: Get release version
      id: get_version
      run: |
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        echo ${{ steps.vars.outputs.version }}
  
    - name: Setup Meteor
      uses: meteorengineer/setup-meteor@v1
      with:
        meteor-release: ${{ matrix.meteor }}

    - name: Build meteor bundle
      run: |
        meteor npm install
        meteor build --directory Tdarr-Bundle  
       
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        CI: true
        RELEASE_VERSION: ${{ steps.vars.outputs.version }}
      with:
        name: xchanclasox/tdarr_aio_test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ubuntu
        buildargs: CI
        tags: "latest,${{ env.RELEASE_VERSION }}"
